fix: explicitly handle a webtiles error case
Occasional exceptions like:

2022-08-30 05:12:17,081 WARN: #5978  Error while handling JSON message (''{"has_focus":true,"generation_id":null,"widget_id"'...')!
Traceback (most recent call last):
  File "/chroot/crawl-master/webserver/webtiles/ws_handler.py", line 1104, in on_message
    self.process.handle_input(message)
  File "/chroot/crawl-master/webserver/webtiles/process_handler.py", line 923, in handle_input
    self.conn.send_message(utf8(msg))
  File "/chroot/crawl-master/webserver/webtiles/util.py", line 89, in wrapped
    return f(*args, **kwargs)
  File "/chroot/crawl-master/webserver/webtiles/connection.py", line 113, in send_message
    self.socket.sendto(utf8(data), self.crawl_socketpath)
FileNotFoundError: [Errno 2] No such file or directory

I'm not sure I exactly understand what is causing this (it seems to be
the same connection repeatedly), but this commit causes the socket to
explicitly close when it does happen.